#!/usr/bin/env bash
# Transfer files from client to server

# Get number of arguments
argc=$#

if [[ $argc -lt 4 ]]; then
	echo 'Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY'
	exit
else
	file="$1"
	ip="$2"
	username="$3"
	ssh_key="$4"
	scp -o StrictHostKeyChecking=no -i "$ssh_key" "$file" "$username@$ip:"
fi
