#!/usr/bin/env bash
# Install and setup nginx server on Ubuntu, setup default page

# Install nginx without prompt
apt update
apt install nginx -y

# Ensure listens on port 80
#  sed -i 's/listen [[:digit:]]*[[:space:]]default_server/listen 80 default_server/'
# sed -i '0,/listen [[:digit:]]*[[:space:]]/s//listen 80 /' /etc/nginx/sites-enabled/default
# sed -i 's/listen [[:digit:]]*[[:space:]]* default_server/ listen 80/' /etc/nginx/sites-available/default
# sed -i 's/listen \[::\]:[[:digit:]]* default_server/ listen [::]:80/' /etc/nginx/sites-available/default


# Get document root directory of server
doc_root="$(grep -v '^#' /etc/nginx/sites-available/default | grep -w 'root' -m 1 | cut -d' ' -f2 | sed 's/;//')"

# create doc_root if not exists
mkdir -p "$doc_root"

# create index.html
echo "Hello World!" > "$doc_root/index.html"


# Allow Nginx HTTP in firewall
ufw allow 'Nginx HTTP'


# Check if configuration is valid and start nginx
# if [[ $(nginx -tq) -eq 0 ]]; then 
# 	# Start nginx server
# 	service nginx restart
# fi

# Always restart nginx
service nginx restart

