#!/usr/bin/env bash
# Edit nginx config, add redirection /redirect_me location

# Install nginx without prompt
apt install nginx -y

# Ensure listens on port 80
#  sed -i 's/listen [[:digit:]]*[[:space:]]default_server/listen 80 default_server/'
sed -i '0,/listen [[:digit:]]*[[:space:]]/s//listen 80 /' /etc/nginx/sites-enabled/default

# Get document root directory of server
doc_root="$(grep -v '^#' /etc/nginx/sites-enabled/default | grep -w 'root' -m 1 | cut -d' ' -f2 | sed 's/;//')"

# create index.html
echo "Hello World!" > "$doc_root/index.html"

# nginx -t

# Check if configuration is valid and start nginx
if [[ $(nginx -tq) -eq 0 && -z "$(pidof nginx)" ]]; then 
	# Start nginx server if not alread running
	nginx
fi

base_location="server_name _;"
redirect_location="location /redirect_me {\n\t\treturn 301 https://google.com;\n\t}"

# Get directive server_name _;, relace it with multiple string of redirect url

sed -i "s|${base_location}|${base_location}\n\n\t${redirect_location}|" /etc/nginx/sites-enabled/default

# Reload nginx, (reload config without stopping)

if [[ $(nginx -tq) -eq 0 ]]; then 
	# reload nginx server
	nginx -s reload
fi

