#!/usr/bin/env bash
# Setup a load balancer in ubuntu server, HAproxy

# update repos
apt-get update -y

# Install HAproxy
# apt-get -y install --no-install-recommends software-properties-common \
# 	&& add-apt-repository -y ppa:vbernat/haproxy-2.0 \
# 	&& apt-get -y install haproxy=2.0.\*
apt install haproxy -y

# Enable HAProxy init script
sed -i '$ a\ENABLED=1' /etc/default/haproxy

# Create a backup of configuration
cp /etc/haproxy/{haproxy.cfg,haproxy.cfg.orig} 

# Edit config to include frontend and backend sections
sed -i '$ r /dev/stdin' /etc/haproxy/haproxy.cfg <<EOF

frontend alxfrontend

	# Receive HTTP traffic on all IP addresses assigned to port 80
	bind *:80

	# Default pool of backend servers
	default_backend alxservers

backend alxservers

	# Define load balancing algorithm
	balance roundrobin

	# check specifies health checks should be performed
	server web-01 54.85.182.135:80 check
	server web-02 100.25.165.99:80 check
EOF

# start haproxy if running
service haproxy restart
