#!/usr/bin/env bash
# Setup a load balancer in ubuntu server, HAproxy

# update repos
apt-get update -y

# Install HAproxy
apt-get -y install --no-install-recommends software-properties-common \
	&& add-apt-repository -y ppa:vbernat/haproxy-2.7 \
	&& apt-get -y install haproxy=2.7.\*

# Enable HAProxy init script
sed -i '$ a\ENABLED=1' /etc/default/haproxy

# Create a backup of configuration
cp /etc/haproxy/{haproxy.cfg,haproxy.cfg.orig} 

# Edit config to include frontend and backend sections
sed -i '$ r /dev/stdin' /etc/haproxy/haproxy.cfg <<EOF

frontend alxfrontend
	# Set proxy mode to http (layer 7)
	mode http

	# Receive HTTP traffic on all IP addresses assigned to port 80
	bind *:80

	# Default pool of backend servers
	default_backend alxservers

backend alxservers
	mode http

	# Define load balancing algorithm
	balance roundrobin

	# check specifies health checks should be performed
	server s1 54.85.182.135:80 check
	server s2 100.25.165.99:80 check
EOF

# start haproxy if running
service haproxy restart
