#!/usr/bin/env bash
# Configure nginx to run on port 80 instead of 8080

# forcefully kill nginx. socket file has been removed
pkill -TERM nginx

# Configure to run on port 80
# /\([^0-9]*\) -> capture all non-numerical
# \([0-9]\{1,\}\) -> capture all numericals in range 1 to inf
# \( default_server\) -> capture default server string
# /\1 -> back reference 1st capture group
# 80 -> put string 80 (replaces 2nd capture group, (port))
# \3 -> back reference 3rd capture group
# /g -> on all lines
sed -i 's/\([^0-9]*\)\([0-9]\{1,\}\)\( default_server\)/\180\3/g' /etc/nginx/sites-enabled/default

# Restart nginx
/etc/init.d/nginx start
