#!/usr/bin/env bash
# Configure nginx to run on port 80 instead of 8080
pkill -TERM nginx
sed -i 's/\([^0-9]*\)\([0-9]\{1,\}\)\( default_server\)/\180\3/g' /etc/nginx/sites-enabled/default
/etc/sandbox_run.sh
