#!/usr/bin/env bash
#Prints 1 to 20
#prints bad luck from china in 4th iteration
#prints bad luck from japan in 9th iteration
#prints bad luck from italy in 17 iteration

i=1
while  [ $i -le 20 ]; do
	echo "$i"
	case $i in 
		4) echo "bad luck from China" ;;
	    9) echo "bad luck from Japan" ;;
	    17) echo "bad luck from Italy";;
	esac
	i=$((i+1))
done
