#!/usr/bin/env bash
# Run nginx as nginx user on port 8080
pkill apache
sed -i 's/\([^0-9]*\)\([0-9]\{1,\}\)\( default_server\)/\18080\3/g' /etc/nginx/sites-enabled/default

# change file ownership to nginx user
chown nginx:nginx /etc/nginx/nginx.conf

# change permission of config file
chmod 644 /etc/nginx/nginx.conf

# start service nginx as nginx user using bash shell
su -s "$(which bash)" nginx -c 'service nginx start'
