#!/usr/bin/env bash
# Run nginx as nginx user
pkill apache2
sed -i 's/\([^0-9]*\)\([0-9]\{1,\}\)\( default_server\)/\18080\3/g' /etc/nginx/sites-available/default
chown nginx:nginx /etc/nginx/nginx.conf
chmod 0644 /etc/nginx/nginx.conf
su -l -s "$(command -v bash)" -c 'service nginx restart' 'nginx'
